version: "3.7"

services:
  drupal:
    image: drupal:latest
    ports:
      - "8080:80"
    volumes:
      - drupal_data:/var/www/html
    depends_on:
      - postgres
    environment:
      DRUPAL_DB_URL: pgsql://drupal:drupal@postgres/drupal

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: drupal
      POSTGRES_PASSWORD: drupal
    volumes:
      - postgres_data:/var/lib/postgresql/data

  phppgadmin:
    image: dockage/phppgadmin:latest
    environment:
      PHP_PG_ADMIN_SERVER_HOST: postgres
      PHP_PG_ADMIN_SERVER_PORT: 5432
      PHP_PG_ADMIN_SERVER_DEFAULT_DB: drupal
      PHP_PG_ADMIN_SERVER_DEFAULT_USER: drupal
      PHP_PG_ADMIN_SERVER_DEFAULT_PASSWORD: drupal
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  drupal_data:
  postgres_data:
